firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "Heya!")
wait(2)
firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "This script is shut down now.")
wait(2)
firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "Damn YouTubers not crediting me.")
wait(2)
firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "Their fault. If you want the real one, join my discord.")
wait(2)
firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "You have to earn it though.")
wait(2)
firesignal(game.ReplicatedStorage.Bricks.Caption.OnClientEvent, "Copied invite to discord, now get out!")
wait(2)
game.Players.LocalPlayer.Character.Humanoid.Health = -100
